Repository ekylibre/ekylibre, pull requests merged in 2019-03, with the labels that each got.

#1941 Feature/animals intervention without animal selected
  app/controllers/backend/interventions_controller.rb
  test/controllers/backend/interventions_controller_test.rb
Labels: Needs QA

#2042 change find to where because find will raise error when record not pr…
  app/views/backend/purchases/_form.html.haml
Labels: Non-compliant

#2045 Handle if record not found during sale credit creation
  app/models/sale.rb
Labels: Non-compliant

#2046 Fixes record dependency for exports show
  app/controllers/backend/exports_controller.rb
  config/locales/eng/action.yml
Labels: Non-compliant

#2080 add missing gaps controller route
  config/routes.rb
Labels: Non-compliant

#2081 add constraint to debt-transfer id not null
  app/models/debt_transfer.rb
Labels: Non-compliant

#2196 Add gem plugin support
  app/controllers/application_controller.rb
  config/initializers/paperclip.rb
  lib/ekylibre/extension.rb
  lib/ekylibre/record/base.rb
  lib/userstamp.rb
  test/lib/config_test.rb
Labels: Under development

#2170 Improve performance of outgoing payment
  app/controllers/backend/outgoing_payment_lists_controller.rb
  app/models/outgoing_payment_list.rb
Labels: Performance

#2198 Auto complete price for current item in new parcel
  app/helpers/backend/parcels_helper.rb
  app/views/backend/parcels/_incoming_item_fields.html.haml
  test/factories/parcel_items.rb
  test/helpers/backend/parcels_helper_test.rb
Labels: Bug, Production
